version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fynlo_postgres
    environment:
      POSTGRES_DB: fynlo_pos
      POSTGRES_USER: fynlo_user
      POSTGRES_PASSWORD: fynlo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fynlo_user -d fynlo_pos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: fynlo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Fynlo Backend API
  backend:
    build: .
    container_name: fynlo_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fynlo_user:fynlo_password@postgres:5432/fynlo_pos
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: