"""create_platform_fees_and_staff_tip_distributions_tables

Revision ID: YYY
Revises: XXX_create_payment_method_settings
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'YYY_create_financial_records_tables' # Placeholder
down_revision = 'XXX_create_payment_method_settings' # Should be the actual ID of the previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create platform_fees table
    op.create_table('platform_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_reference', sa.String(), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('processor_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_paid_processor_fee', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_fees_id'), 'platform_fees', ['id'], unique=False)
    op.create_index(op.f('ix_platform_fees_order_reference'), 'platform_fees', ['order_reference'], unique=False)

    # Create staff_tip_distributions table
    op.create_table('staff_tip_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_reference', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('tip_amount_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_charge_deduction', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.0')),
    sa.Column('transaction_fee_impact_on_tip', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.0')),
    sa.Column('tip_amount_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distribution_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_tip_distributions_id'), 'staff_tip_distributions', ['id'], unique=False)
    op.create_index(op.f('ix_staff_tip_distributions_order_reference'), 'staff_tip_distributions', ['order_reference'], unique=False)
    op.create_index(op.f('ix_staff_tip_distributions_staff_id'), 'staff_tip_distributions', ['staff_id'], unique=False)
    op.create_index('idx_staff_tip_order_staff', 'staff_tip_distributions', ['order_reference', 'staff_id'], unique=False) # As defined in model

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop staff_tip_distributions table
    op.drop_index('idx_staff_tip_order_staff', table_name='staff_tip_distributions')
    op.drop_index(op.f('ix_staff_tip_distributions_staff_id'), table_name='staff_tip_distributions')
    op.drop_index(op.f('ix_staff_tip_distributions_order_reference'), table_name='staff_tip_distributions')
    op.drop_index(op.f('ix_staff_tip_distributions_id'), table_name='staff_tip_distributions')
    op.drop_table('staff_tip_distributions')

    # Drop platform_fees table
    op.drop_index(op.f('ix_platform_fees_order_reference'), table_name='platform_fees')
    op.drop_index(op.f('ix_platform_fees_id'), table_name='platform_fees')
    op.drop_table('platform_fees')

    # ### end Alembic commands ###
