# DigitalOcean App Spec for Fynlo POS Backend
name: fynlo-pos-backend
region: lon # London region, as specified for the database

# Define the services
services:
  - name: api
    # Use Docker for consistent build environment
    dockerfile_path: Dockerfile
    source_dir: backend
    github:
      repo: Lucid-Directions/cashapp-fynlo
      branch: main
    # Environment variables
    envs:
      - key: API_HOST
        value: "0.0.0.0"
      - key: API_PORT
        value: "8000" # App Platform will map this to 80/443 externally
      - key: API_RELOAD
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      # VPC SECURE DATABASE CONNECTION (Configure in App Platform UI)
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET # Set value in DigitalOcean App Platform dashboard
      # VPC SECURE REDIS CONNECTION (Configure in App Platform UI)  
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET # Set value in DigitalOcean App Platform dashboard
      # Add any other non-secret environment variables from your .env file here
      # For example:
      # - key: SOME_OTHER_CONFIG
      #   value: "some_value"
    instance_size_slug: basic-s # Increase to basic-s for sufficient memory as per investigation
    instance_count: 1
    # HTTP routes
    routes:
      - path: / # Route all traffic to this service
    # Health check - temporarily disabled until database secrets configured
    # health_check:
    #   http_path: /health # Path defined in Dockerfile HEALTHCHECK
    #   initial_delay_seconds: 60  # Longer startup time
    #   period_seconds: 30          # Less frequent checks
    #   timeout_seconds: 10         # Longer timeout
    #   failure_threshold: 5        # More retries before failing
    #   success_threshold: 1
    # Port for the service to listen on internally
    http_port: 8000

# Define jobs that run during deployment
# NOTE: Migration job disabled until database secrets are configured
# jobs:
#   - name: migrate
#     kind: PRE_DEPLOY # Run before deploying the 'api' service
#     # Use same Docker setup as main service
#     dockerfile_path: Dockerfile
#     source_dir: backend
#     github:
#       repo: Lucid-Directions/cashapp-fynlo
#       branch: main
#     # Command to run for migrations
#     run_command: alembic upgrade head
#     # Environment variables for the job (needs database access)
#     envs:
#       # VPC SECURE DATABASE CONNECTION for migrations (Configure in App Platform UI)
#       - key: DATABASE_URL
#         scope: RUN_TIME
#         type: SECRET # Set value in DigitalOcean App Platform dashboard
#     instance_size_slug: basic-xxs # Migrations usually don't need large instances

# Optional: Define databases, static sites, etc.
# For this deployment, databases are already provisioned.

# Alerting (optional, configure in DigitalOcean UI or add spec here)
# alerts:
# - rule: DEPLOYMENT_FAILED
# - rule: DOMAIN_FAILED

# Custom domain (optional, configure in DigitalOcean UI or add spec here)
# domains:
# - domain: your-app-custom-domain.com
#   type: PRIMARY # or ALIAS
#   zone: your-app-custom-domain.com # if using DigitalOcean DNS
#   minimum_tls_version: "1.2"
