name: Backup Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at minute 0
  workflow_dispatch:     # Allows you to run manually too

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This makes sure you get the full git history

      - name: Mirror push to backup repository
        env:
          GITHUB_TOKEN: ${{ secrets.BACKUP_REPO_PAT }}
        run: |
          git config --global user.email "arnaud_decube@hotmail.com"
          git config --global user.name "Lucid-Directions"

          # Configure git to use the token
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

          # Add the backup repo as a remote called 'backup'
          git remote add backup https://github.com/Lucid-Directions/flynlo-backup.git

          # Push all branches, tags, and refs
          git push --mirror backup
