name: Test Token Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test repository access
        run: |
          echo "Testing token access to backup repository..."
          curl -H "Authorization: token ${{ secrets.BACKUP_REPO_PAT }}" \
               https://api.github.com/repos/Lucid-Directions/flynlo-backup \
               || echo "Failed to access repository"